version: '2.2'

services:
  mailserver:
    build: ./servermail
    environment:
      - DOMAIN_NAME=passbolt.poc
      - ALLOWED_NETWORKS=172.50.50.0/24
    networks:
      lan:
        ipv4_address: 172.50.50.10
  
  webmail:
    environment:
      - EMAIL_SERVER_HOST=172.50.50.10
      - PORT=80
      - EMAIL_DOMAIN=passbolt.poc
      - TOKEN_SECRET=123123123123
      - SESSION_EXPIRE_IN_MINUTES=5
    build: ./webmail
    networks:
      lan:
        ipv4_address: 172.50.50.20

networks:
  lan:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.50.0/24